name: Flutter CI

on:
  push:
    branches: [prod, staging, dev]
  pull_request:
    branches: [prod, staging, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
